"""add composite index        
  api_key_id_created_at on usage_records

Revision ID: 3b09b71e0564
Revises: a07ae9cb900c
Create Date: 2026-02-15 20:47:11.192435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b09b71e0564'
down_revision: Union[str, None] = 'a07ae9cb900c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_usage_records_api_key_id_created_at', 'usage_records', ['api_key_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_records_api_key_id_created_at', table_name='usage_records')
    # ### end Alembic commands ###
